### ISSUE TITLE
spatial coordinates

### ISSUE THREAD

**Issue by shcrela** [alchem0x2A/py-wdf-reader#2]
Hi, Thanks a lot for the script.
I wanted to ask if you know how could one retrieve the spatial coordinates from a map scan (or from a depth profile)?
I'd say those informations would be stored only as the steps between the measurements. Those should be enough to reconstruct all the points (considering the measurement type - map, snake, depth...)

**Comment by DancingQuanta** [comment]
Gwyddion, a open source data viewer and analysis tool, can view WDF files quite well.
The source code for the parser is [here](https://sourceforge.net/p/gwyddion/code/HEAD/tree/trunk/gwyddion/modules/file/renishaw.c). 
Maybe, if someone have time to port this to python.

**Comment by alchem0x2A** [comment]
Hi, a lot time has passed that I have time to work on this project again. Starting from version 0.1.0 the parser can get the x- and y-positions of the WDF file by reading the ORGN datablock.

Examples:
```python
from renishawWiRE import WDFReader
wdf = WDFReader("path/to/some.wdf")
print(wdf.xpos, wdf.ypos)
```

Both xpos and ypos are with length of self.count. Testing / feedback greatly welcome!
