### ISSUE TITLE
Mapping error: 'JpegImageFile' object has no attribute 'getexif' 

### ISSUE THREAD

**Issue by SandLabore** [alchem0x2A/py-wdf-reader#36]
Hallo,

thank you very much for all your effort in programming the wdf reader.
I have a problem in opening files based on a mapping. In this case, the following error occurs: 'JpegImageFile' object has no attribute 'getexif'. 
I'm using files which were generated with Wire 4.3 to 5.2, and Python 3.7 Environment in Windows.
Single spectra and depth files are working fine.

Best regards,
SandLabore

**Comment by alchem0x2A** [comment]
I believe the issue is similar to https://github.com/Tessellate-Imaging/monk_v1/issues/60 which can be a bug in the `Pillow` package. I'm not sure whether that's caused by implementation on windows or not but you may try if downgrading the `pillow` version works.

**Comment by SandLabore** [comment]
I tried to solve the problem, but only destroyed my Anaconda. However, after reinstallation with everything in the newest version, it is now working :-) 
Thank you for your fast answer.

**Comment by alchem0x2A** [comment]
you're welcome!
