### ISSUE TITLE
New Data and Unit types

### ISSUE THREAD

**Issue by rodsmithMB** [alchem0x2A/py-wdf-reader#38]
The StreamHR Mapping feature on newer models has a new DataType and a new UnitType that are not identified.  These should be:

ExposureTime = 27
Microseconds = 25

A sample printout from the **origin_list_header** from a StreamHR Mapping file after a manual fix:

[False,
 <DataType.ExposureTime: 27>,
 <UnitType.Microseconds: 25>,
 'act exp time',
 array([ 98801., 100000.,  97502., ...,  99051., 101051., 101150.])]

**Comment by alchem0x2A** [comment]
Hi @rodsmithMB, thanks for providing the feedback! I think it should be a straightforward fix to `type.py`. If that's ok for you you can directly PR to the master branch.

as mentioned also in #35, it would be great to include a test for newer versions of renishaw files. If you have some files that does not have issues with IP, then we can include one for unittest. Let me know if that works for you

**Comment by rodsmithMB** [comment]
Sent. I have a file I can send. Where would you like it uploaded/sent?

**Comment by alchem0x2A** [comment]
Thx a lot for the PR! You can add it as attachment to this issue and I'll modify the example codes. The file will finally appear as the binary release that can be downloaded for testing.

**Comment by rodsmithMB** [comment]
[StreamHRrapide.zip](https://github.com/alchem0x2A/py-wdf-reader/files/6708999/StreamHRrapide.zip)
