### ISSUE TITLE
License type mismatch

### ISSUE THREAD

**Issue by ORscripts** [alchem0x2A/py-wdf-reader#44]
The LICENSE file and the README.md state that MIT license applies, while in PyPI the license is GPLv3.
This could occur because the license is set to "GPLv3" in https://github.com/alchem0x2A/py-wdf-reader/blob/master/setup.py#L45

**Comment by alchem0x2A** [comment]
Hi Oleg, thanks a lot for pointing this out. #45 fixed this and the pypi page should show the correct MIT license.
